### ISSUE TITLE
你好，请问可以提供数据集吗？网上没找到

### ISSUE THREAD

**Issue by LCG22** [guangxush/CCKS2019_Task3#3]

**Comment by guangxush** [comment]
https://www.biendata.com/competition/ccks_2019_ipre/data/
数据集下载链接，需要登陆

**Comment by LCG22** [comment]
已经过了比赛时间了，下载不了

**Comment by guangxush** [comment]
我可以下载，给你个网盘链接
https://pan.baidu.com/s/1gtq3FEMx4_eAFmZqyn844Q  提取码8gd2
https://www.dropbox.com/s/m7n0t1ce6db9jhq/open_data.zip?dl=0
